version: "3.9"
services:
  frontend:
    build:
      context: ./setting/frontend
    ports:
      - 3030:3000
    volumes:
      - ./frontend:/app
    command: bash -c "npm run dev"
    # command: bash -c "npm run build && npm run start"
    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  backend:
    build:
      context: ./setting/backend
    volumes:
      - ./backend:/work
  nginx:
    build:
      context: ./setting/nginx
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./setting/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: project
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    volumes:
      - datavolume:/var/lib/mysql
      - ./setting/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=project
      - PMA_PASSWORD=project
volumes:
  datavolume: {}
